spring:
  database:
    url: jdbc:postgresql://ewm-ru.practicum.service:5432/postgres
    driverClassName: org.postgresql.Driver
    username: user
    password: pass

ru.practicum.client:
  server:
    host: stats-server
    port: 9090