server:
  port: 8080

stats-server:
  url: http://stats-server:9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        check_nullability: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm-service
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

---
spring:
  config:
    activate:
      on-profile: ci,test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm;
    username: test
    password: test
  sql:
    init:
      mode: always
ru.practicum.client:
  server:
    host: stats-server
    port: 9090