server:
  port: 9090

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update #update | none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never  #always | never

  datasource:
    url: jdbc:postgresql://stats-db:5432/stat #jdbc:postgresql://stats-db:5432/stat | jdbc:postgresql://localhost:4321/stat
    username: postgres
    password: postgres

---

#spring:
#  config:
#    activate:
#      on-profile: "ci,test"
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:stats-server
#    username: test
#    password: test