server:
  port: 9090

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stat
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile: "ci,test" # Или ["ci", "test"] - зависит от версии Spring Boot
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stats-server
    username: test
    password: test